version: "3.7"

services:

  db-user:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
