files:
  path: /home/lucas/app/usp/mac0499/perf/msg-files/

server:
  compression:
    enabled: true

springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    disable-swagger-default-url: true
    path: "/"

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

amqp:
  queue:
    name: default
