version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  rabbitmq-producer:
    build: ./rabbitmq-producer
    ports:
      - "8080:8080"
    environment:
      BROKER_HOST: "rabbitmq"
      BROKER_PORT: 5672
      BROKER_USER: "guest"
      BROKER_PASS: "guest"
    depends_on:
      - rabbitmq

  rabbitmq-consumer:
    build: ./rabbitmq-consumer
    restart: unless-stopped
    environment:
      BROKER_HOST: "rabbitmq"
      BROKER_PORT: 5672
      BROKER_USER: "guest"
      BROKER_PASS: "guest"
    depends_on:
      - rabbitmq
