version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  rabbitmq-producer:
    build: ./rabbitmq-producer
    ports:
      - "8080:8080"
    environment:
      BROKER_HOST: "amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      - rabbitmq

  rabbitmq-consumer:
    build: ./rabbitmq-consumer
    environment:
      BROKER_HOST: "amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      - rabbitmq
